name: Windows D3D12 NVIDIA DXC

permissions:
  contents: read
  checks: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0-12 * * 1-5' # run every 30 minutes overnight
    - cron: '0 * * * 0,6' # run every 30 minutes on weekends

jobs:
  Windows-D3D12-NVIDIA-DXC:
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
      SKU: GPU-NV
      Test-Clang: Off
      BuildType: Debug
      TestTarget: check-hlsl-d3d12
      HLSLTest-branch: ${{ github.ref }}
      LLVM-ExtraCMakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
